Python3 tweak
I saw an exception I wanted to take care of:

  [ubuntu@pfuntner-ubuntu CCC-2030]$ json -linear < clamscan.json | headtail
  Traceback (most recent call last):
    File "/home/ubuntu/bin/json", line 348, in <module>
      root = applyFilters(root)
    File "/home/ubuntu/bin/json", line 231, in applyFilters
      ret = applyFilters(root[key])
    File "/home/ubuntu/bin/json", line 224, in applyFilters
      for key in keys:
  RuntimeError: dictionary changed size during iteration
  [ubuntu@pfuntner-ubuntu CCC-2030]$

I incorrectly used `-linear` when I wanted `--linear` so that was my problem.  Additionally, the root object in this case was a dictionary so --linear wasn't even appropriate but exceptions like this should not happen.