Python 3: Problem using br on Windoze
I tried a simple command like:

  $ date | br
  Traceback (most recent call last):
    File "/home/John Pfuntner/bin/br", line 84, in <module>
      os.write(fd, add_crs(sys.stdin.read()))
  TypeError: a bytes-like object is required, not 'str'
  $

This fixes it for Windoze.  I'll have to make sure it works on Unix too.